### ISSUE TITLE
Image List

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#1]
## Value Proposition

- As an A.I. Artist/User,
- I want to see a list of images that have been uploaded to the web-app
- So that I can choose one to rate it in different categories...
​
## Description

- The user will be presented with a list of uploaded images and can choose one to rate based on different categories, such as clarity, composition, and color...

Current UserStory is marked in a *GREEN* block.
![userstory1](https://user-images.githubusercontent.com/121774259/223168756-39b802d3-2f62-42b5-a9ca-efd1972eabfa.png)

## Acceptance Criteria

- [x] Display a scrollable list of the 20 A.I. generated Images (atm saved in the project)
- [x] Each list item consists of an image that works as a link to the details page.
--> Later: Allow users to add new images to the list...

​
## Tasks

- [x] show all created images in a scrollable list...
- [x] dynamically render a list of the saved images
​

**Comment by Marcel-FR** [comment]
LGTM!

**Comment by MartinK1983** [comment]
Good Work
