### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#10]
## Value Proposition

**As a user, I want to be able to easily navigate through different sections of the website, so that I can quickly find the information I am looking for.

## Description

The user will be able to navigate through different sections of the website. The navigation menu will be designed to be simple and easy to use, with clear labels for each section of the website.

The navigation menu will include links to the most important sections of the website, such as the homepage/overview page, and showcase page. When the user clicks on a link in the navigation menu, they will be taken directly to the corresponding page.

The navigation menu will be fixed at the top of the page, so that it is always visible and easily accessible. 

Current UserStory is marked in a GREEN block.​
![Image](https://user-images.githubusercontent.com/121774259/224676687-deceff68-f975-4242-a270-ac279ddcf90c.png)

​

## Acceptance Criteria

- [x] Add a navigation menu to the top.
- [x]  The navigation menu should include links to the most important sections of the website.
- [x]  The navigation menu should be designed to be simple and easy to use, with clear labels for each section of the website.
- [x]  The navigation menu should be fixed at the top of the page and always visible.

## Tasks

- [x]  Create a simple, minimalist design for the navigation menu.
- [x]  Add links to the most important sections of the website in the navigation menu.
- [x]  Make sure the navigation menu is fixed at the top of the page and always visible.

**Comment by SarahWett** [comment]
Good work! :)
