### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#17]
## Value Proposition

**As a developer, I want to ensure that the code is working as expected, so that I can identify and fix any issues or bugs.
​

## Description

The developer will write a total of 3 component tests for the project. These tests will help ensure that the code is functioning as expected and will identify any issues or bugs that need to be fixed.
​

## Acceptance Criteria

- [x] At least 3 component tests have been written.
- [x] All tests have been successfully executed and passed.

## Tasks

- [x] Write 3 component tests for the project.
- [x] Execute all tests and ensure that they have passed.

**Comment by CTGitWhiz** [comment]
No QA required - doesn't make sense -TESTING
