### ISSUE TITLE
ImageDetails

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#3]
## Value Proposition

**As a User
**As a User, I want to click on an Image in the ImageList and see a larger version of the selected image in a new details page so that I can view the selected image in its original or larger size.
​

## Description

When a user clicks on an image from the ImageList component, they will be redirected to a new details page where they can view the selected image in its original or larger size. The details page will only display the selected image and it will be centered on the page.

​Current UserStory is marked in a GREEN block.
![Screenshot 2023-03-08 at 12 27 55](https://user-images.githubusercontent.com/121774259/223701855-6d61a09b-a46c-4b7d-a86d-25a4903fe5e0.png)

## Acceptance Criteria

- [x] When a user clicks on an image in the ImageList, they are taken to a new details page.
- [x] The details page displays only the selected image.
- [x] The selected image is displayed in its original size or a larger size.
- [x] The selected image is centered on the page.​

## Tasks

- [x] Create a new ImageDetails component.
- [x] Add a Link component to each image in the ImageList component that links to the "ImagePage" component and passes the selected image's ID as a query parameter.
- [x] Construct the URL for the selected image based on the ID.
- [x] Use the Next.js Image component to display the selected image in its original size or a larger size.
- [x] Center the selected image on the page in the "ImagePage" component.
      ​

**Comment by SarahWett** [comment]
Pretty & very clean design. :)
Functionality approved.
