### ISSUE TITLE
ImageDetails - Slider/RangeInput - Buttons

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#5]
## Value Proposition

**As a User
**I want to be able to evaluate an image based on different categories via slider buttons. I want to be able to save my individual input for each category and return to the homepage after saving my evaluation.
​

## Description

The user can evaluate an image based on different categories using slider buttons. There will be five slider buttons with ranges from 0-10 for each category. After the user has evaluated the image for all categories, they can save their individual input for each category and return to the homepage.

Current UserStory is marked in a GREEN block.​
![Screenshot 2023-03-10 at 15 36 21](https://user-images.githubusercontent.com/121774259/224343286-239ff643-01eb-4cb2-8b1e-e2c589d8df49.png)

## Acceptance Criteria

- [x] Display 5 slider buttons with ranges from 0-10 for each category.
- [x] Allow users to evaluate an image based on the slider buttons for each category.
- [x] Display two buttons, one to return to the homepage and one to save the individual input for each category.
- [x] After the user saves their evaluation, redirect them to the homepage.
      ​

## Tasks

- [x] Add five slider buttons with ranges from 0-10 for each category.
- [x] Add two buttons, one to return to the homepage and one to save the evaluation.
- [x] On save, redirect the user to the homepage and save the individual input for each category.
- [x] Style the component to make it visually appealing.
