### ISSUE TITLE
Display Best Rated Images for Each Category on a New Page

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#7]
## Value Proposition

**As a User I want to be able to see the best-rated image for each category so that I can compare my evaluations and see which image performed the best overall.​​

## Description

The user will be able to access a separate page that shows the best-rated image for each category based on the most recent evaluation, which is stored in local storage. The page will display each category and the image with the highest evaluation score will be shown. If multiple images have the same highest score for a category, the one that was evaluated most recently will be shown. 
​
Current UserStory is marked in a GREEN block.​
![Screenshot 2023-03-10 at 17 18 20](https://user-images.githubusercontent.com/121774259/224427337-ffc506ce-207e-414f-abd7-d7a82db3bbc4.png)

## Acceptance Criteria

- [x] Create a separate page for the best-rated images for each category.
- [x]  Display the five Category on the page.
- [x]  For each category, display the image with the highest evaluation score based on the most recent evaluation.
- [x]  If multiple images have the same highest score for a category, display the one that was evaluated most recently.

## Tasks

- [x] Create a separate page for the best-rated images.
- [x]  Fetch past evaluations from local storage and determine the highest-rated image for each category based on the most recent evaluation.
- [x]  Display the highest-rated image for each category on the page.
- [x]  Add styles to make the page visually appealing.
