### ISSUE TITLE
Ability to Delete Images from Homepage and Local Storage.

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#8]
## Value Proposition

**As a User I want to be able to delete an image from the homepage, so that I can remove irrelevant images.

## Description

The user will be able to delete an image from the homepage. 
The user will be able to delete an image by clicking on a delete button that will be added next to each image.

Current UserStory is marked in a GREEN block.​
<img width="363" alt="Screenshot 2023-03-10 at 22 13 49" src="https://user-images.githubusercontent.com/121774259/224429573-78723b21-6d07-4134-8de1-bcf4b99b8bee.png">
​

## Acceptance Criteria

- [x] Add a delete button next to each image on the homepage.
- [x]  When the user clicks on the delete button, the corresponding image should be removed from the homepage.
- [x]  The page should update immediately to reflect the changes.
​

## Tasks

- [x] Add a delete button to each image on the homepage.
- [x]  Implement a function that removes an image from the homepage.
- [x]  Update the page immediately after an image is deleted to reflect the changes.
