### ISSUE TITLE
Information Tooltip

### ISSUE THREAD

**Issue by CTGitWhiz** [CTGitWhiz/capstone-project#9]
## Value Proposition

**As a User, I want to be able to see a small info icon next to the image and access more information about the rating categories, so that I can better understand how to evaluate the image.

## Description

The user can see the image on the screen with a small info icon next to it. Clicking on the info icon displays a tooltip with brief descriptions of the five best image evaluation/rating categories that the user can rate/judge on. Each category is clearly labeled with a name and has a brief description to help the user better understand how to evaluate the image. The tooltip disappears when the user clicks outside of it.

Current UserStory is marked in a GREEN block.​
![Image](https://user-images.githubusercontent.com/121774259/224676813-d9d4efaa-fe67-4b68-a328-c5f4b98992d9.png)

## Acceptance Criteria

- [x] Display the info icon next to the image.
- [x] When the user clicks on the info icon, a tooltip should appear with brief descriptions of the five best image evaluation/rating categories.
- [x] Each category should be clearly labeled with a name and have a brief description to help the user better understand how to evaluate the image.
- [x] The tooltip should disappear when the user clicks outside of it.

## Tasks

- [x] Choose the five best image evaluation/rating categories and their brief descriptions.
- [x] Add a small info icon next to the image.
- [x] Implement a function that displays a tooltip with brief descriptions of the five best image evaluation/rating categories when the user clicks on the info icon.
- [x] Clearly label each category with a name to help the user better understand how to evaluate the image.

**Comment by SarahWett** [comment]
Good One!
